unet:
  base_channel_count: 16 
train:
  num_epochs: 501
  batch_size: 128 
  dataset: elevation
  data_root: ./data/elevation
  model_save_dir: ./result/elevation_experiment-2

eval:
  val_epochs: 20